version: '3'
services:
  angular-app:
    image: angular-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/usr/src/app/src
    environment:
      - NODE_ENV=development
      
  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "4200:80"
    depends_on:
      - angular-app